import  SearchBox from './Searchbox';
import { Helmet } from "react-helmet";
import TagBox from "../../components/TagBox";

const popularTags = [{"name":"photography"},
  {"name":"nature"},{"name":"portrait"},
  {"name":"fashion"},{"name":"wallpaper"},
  {"name":"surreal"},
  {"name":"travel"},
  {"name":"landcape"},
  {"name":"cityscape"}
]

const Explore = (props) => {

  return (
    <>
        <Helmet>
          <title>Explore sexy Ai girls</title>
          <link rel="canonical" href={'https://sexyaigirs.fun/explore'} />
          <meta property="og:url" content="https://artgallery.fun/explore" />
          <meta property="og:description"
     content="Collection of erotic and nude photos generated by Ai. Take a look at large captivating collection of relastic photos generated by Artificial inteligence."
     />
        </Helmet>

<div className="col-md-6 m-auto p-2">    
<SearchBox />
<div className="text-center p-1">
  <h1 className="h5">
    Popular Tags
  </h1>
<TagBox tags={popularTags} />
  
</div>
</div>
</>
  )
};

export default Explore;